// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDonLogistics.Data;

#nullable disable

namespace QuanLyDonLogistics.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251013161014_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDonLogistics.Data.HangHoa", b =>
                {
                    b.Property<Guid>("MaHh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MoTa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenHh")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaHh");

                    b.ToTable("HangHoa");
                });
#pragma warning restore 612, 618
        }
    }
}
